services:
  db:
    image: mysql:latest
    container_name: random_memo
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3308:3306"
    volumes:
      - ./db_data:/var/lib/mysql
  app:
    build: .
    container_name: memo
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
  frontend:
    build: ./memo-front
    ports:
      - "5173:80"
    depends_on:
      - app
volumes:
  db_data: