services:
  db:
    image: mysql:latest
    container_name: random_memo
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: memos
    ports:
      - "3308:3306"
    volumes:
      - ./db_data:/var/lib/mysql
  app:
    build: .
    container_name: memo
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  db_data: